// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonResto.Data;

#nullable disable

namespace MonResto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223113242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MonResto.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("MonResto.Models.CommandeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.ToTable("CommandeItems");
                });

            modelBuilder.Entity("MonResto.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Entrée",
                            Description = "Laitue, poulet, parmesan, croûtons",
                            Disponible = true,
                            Nom = "Salade César",
                            Prix = 85.00m
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Entrée",
                            Description = "Gratinée au fromage",
                            Disponible = true,
                            Nom = "Soupe à l'oignon",
                            Prix = 65.00m
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Plat",
                            Description = "Poulet aux olives et citron confit",
                            Disponible = true,
                            Nom = "Tajine poulet",
                            Prix = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Plat",
                            Description = "Viandes variées et légumes",
                            Disponible = true,
                            Nom = "Couscous royal",
                            Prix = 150.00m
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "Plat",
                            Description = "Feuilleté sucré-salé",
                            Disponible = true,
                            Nom = "Pastilla au poulet",
                            Prix = 95.00m
                        },
                        new
                        {
                            Id = 6,
                            Categorie = "Dessert",
                            Description = "Dessert italien classique",
                            Disponible = true,
                            Nom = "Tiramisu",
                            Prix = 45.00m
                        },
                        new
                        {
                            Id = 7,
                            Categorie = "Dessert",
                            Description = "Dessert français traditionnel",
                            Disponible = true,
                            Nom = "Crème brûlée",
                            Prix = 40.00m
                        },
                        new
                        {
                            Id = 8,
                            Categorie = "Boisson",
                            Description = "33cl",
                            Disponible = true,
                            Nom = "Coca-Cola",
                            Prix = 15.00m
                        },
                        new
                        {
                            Id = 9,
                            Categorie = "Boisson",
                            Description = "Pressé minute",
                            Disponible = true,
                            Nom = "Jus d'orange frais",
                            Prix = 25.00m
                        },
                        new
                        {
                            Id = 10,
                            Categorie = "Boisson",
                            Description = "Traditionnel marocain",
                            Disponible = true,
                            Nom = "Thé à la menthe",
                            Prix = 15.00m
                        });
                });

            modelBuilder.Entity("MonResto.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroTable")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionId")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumeroTable = 1,
                            QrCodeUrl = "table-1",
                            Statut = "Libre"
                        },
                        new
                        {
                            Id = 2,
                            NumeroTable = 2,
                            QrCodeUrl = "table-2",
                            Statut = "Libre"
                        },
                        new
                        {
                            Id = 3,
                            NumeroTable = 3,
                            QrCodeUrl = "table-3",
                            Statut = "Libre"
                        },
                        new
                        {
                            Id = 4,
                            NumeroTable = 4,
                            QrCodeUrl = "table-4",
                            Statut = "Libre"
                        },
                        new
                        {
                            Id = 5,
                            NumeroTable = 5,
                            QrCodeUrl = "table-5",
                            Statut = "Libre"
                        },
                        new
                        {
                            Id = 6,
                            NumeroTable = 6,
                            QrCodeUrl = "table-6",
                            Statut = "Libre"
                        });
                });

            modelBuilder.Entity("MonResto.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Administrateur Principal",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Jean Dupont",
                            Password = "serveur123",
                            Role = "Serveur",
                            Username = "serveur1"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Marie Cuisinier",
                            Password = "chef123",
                            Role = "Cuisinier",
                            Username = "chef1"
                        });
                });

            modelBuilder.Entity("MonResto.Models.CommandeItem", b =>
                {
                    b.HasOne("MonResto.Models.Commande", null)
                        .WithMany("Items")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonResto.Models.Commande", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
